//! ZeroMQ PUB/SUB transport. Mirrors ruby_zmq_framework's ZeroMQBus: every
//! node owns one PUB socket (bound to its own port) and one SUB socket
//! (connected to each peer, subscribed to everything, filtered on receipt).
//! Wire format: a two-frame multipart message, [topic, json], per PROTOCOL.md.
const std = @import("std");
const c = @cImport({
    @cInclude("zmq.h");
});

pub const BusError = error{ZmqError};

/// How long the listener blocks in zmq_poll before looping, in milliseconds.
const POLL_TIMEOUT_MS: c_long = 100;

/// A local subscriber: some node's handleMessage, type-erased. `callback`
/// is generated by framework.zig's boot() as a comptime trampoline back to
/// the concrete node type, so Bus itself never needs to know node types.
pub const Subscriber = struct {
    ptr: *anyopaque,
    callback: *const fn (ptr: *anyopaque, topic: []const u8, payload: std.json.Value) void,
};

/// A mutex that the same thread may re-lock without deadlocking. Needed
/// because `dispatch` holds the lock for the whole subscriber iteration
/// (serializing handlers across the listener thread and any thread calling
/// publish), and a handler that calls broadcast() from inside handleMessage
/// re-enters that same lock on the same thread.
const RecursiveMutex = struct {
    mutex: std.Thread.Mutex = .{},
    cond: std.Thread.Condition = .{},
    owner: ?std.Thread.Id = null,
    depth: u32 = 0,

    fn lock(self: *RecursiveMutex) void {
        const tid = std.Thread.getCurrentId();
        self.mutex.lock();
        defer self.mutex.unlock();
        while (self.owner != null and self.owner.? != tid) self.cond.wait(&self.mutex);
        self.owner = tid;
        self.depth += 1;
    }

    fn unlock(self: *RecursiveMutex) void {
        self.mutex.lock();
        defer self.mutex.unlock();
        self.depth -= 1;
        if (self.depth == 0) {
            self.owner = null;
            self.cond.signal();
        }
    }
};

pub const Bus = struct {
    allocator: std.mem.Allocator,
    ctx: *anyopaque,
    pub_sock: *anyopaque,
    sub_sock: *anyopaque,
    /// The port actually bound — differs from the requested port when 0
    /// (OS-assigned ephemeral) was requested. Read back via getsockopt.
    port: u16,
    subscribers: std.StringHashMap(std.ArrayList(Subscriber)),
    lock: RecursiveMutex = .{},
    running: std.atomic.Value(bool) = std.atomic.Value(bool).init(true),
    listener: ?std.Thread = null,
    closed: bool = false,

    /// my_port may be 0 to bind an OS-assigned ephemeral port (read back via
    /// .port). peer entries are "host:port" or a full endpoint ("tcp://...").
    /// Pass bind_host "0.0.0.0" to accept peers from other machines.
    pub fn init(allocator: std.mem.Allocator, my_port: u16, peers: []const []const u8, bind_host: []const u8) !*Bus {
        const self = try allocator.create(Bus);
        errdefer allocator.destroy(self);

        const ctx = c.zmq_ctx_new() orelse return BusError.ZmqError;
        errdefer _ = c.zmq_ctx_term(ctx);

        const pub_sock = c.zmq_socket(ctx, c.ZMQ_PUB) orelse return BusError.ZmqError;
        errdefer _ = c.zmq_close(pub_sock);

        var bind_buf: [128]u8 = undefined;
        const bind_endpoint = if (my_port == 0)
            try std.fmt.bufPrintZ(&bind_buf, "tcp://{s}:*", .{bind_host})
        else
            try std.fmt.bufPrintZ(&bind_buf, "tcp://{s}:{d}", .{ bind_host, my_port });
        if (c.zmq_bind(pub_sock, bind_endpoint) != 0) return BusError.ZmqError;

        const sub_sock = c.zmq_socket(ctx, c.ZMQ_SUB) orelse return BusError.ZmqError;
        errdefer _ = c.zmq_close(sub_sock);

        for (peers) |peer| {
            var ep_buf: [256]u8 = undefined;
            const endpoint = try peerEndpoint(&ep_buf, peer);
            if (c.zmq_connect(sub_sock, endpoint) != 0) return BusError.ZmqError;
        }
        if (c.zmq_setsockopt(sub_sock, c.ZMQ_SUBSCRIBE, "", 0) != 0) return BusError.ZmqError;

        self.* = .{
            .allocator = allocator,
            .ctx = ctx,
            .pub_sock = pub_sock,
            .sub_sock = sub_sock,
            .port = try readBoundPort(pub_sock),
            .subscribers = std.StringHashMap(std.ArrayList(Subscriber)).init(allocator),
        };

        self.listener = try std.Thread.spawn(.{}, listenerLoop, .{self});
        return self;
    }

    /// Stops the listener thread and releases both sockets and the context.
    /// Stop anything still publishing on this bus first (heartbeats, reader
    /// threads): publishing on a closed bus is undefined. Idempotent.
    pub fn close(self: *Bus) void {
        if (self.closed) return;
        self.closed = true;
        self.running.store(false, .release);
        if (self.listener) |t| t.join();

        var zero: c_int = 0;
        _ = c.zmq_setsockopt(self.sub_sock, c.ZMQ_LINGER, &zero, @sizeOf(c_int));
        _ = c.zmq_setsockopt(self.pub_sock, c.ZMQ_LINGER, &zero, @sizeOf(c_int));
        _ = c.zmq_close(self.sub_sock);
        _ = c.zmq_close(self.pub_sock);
        _ = c.zmq_ctx_term(self.ctx);

        var it = self.subscribers.iterator();
        while (it.next()) |entry| {
            self.allocator.free(entry.key_ptr.*);
            entry.value_ptr.deinit();
        }
        self.subscribers.deinit();
    }

    pub fn subscribe(self: *Bus, topic: []const u8, sub: Subscriber) !void {
        self.lock.lock();
        defer self.lock.unlock();

        const gop = try self.subscribers.getOrPut(topic);
        if (!gop.found_existing) {
            gop.key_ptr.* = try self.allocator.dupe(u8, topic);
            gop.value_ptr.* = std.ArrayList(Subscriber).init(self.allocator);
        }
        try gop.value_ptr.append(sub);
    }

    pub fn publish(self: *Bus, topic: []const u8, payload: anytype) !void {
        const json = try std.json.stringifyAlloc(self.allocator, payload, .{});
        defer self.allocator.free(json);

        if (c.zmq_send(self.pub_sock, topic.ptr, topic.len, c.ZMQ_SNDMORE) == -1) return BusError.ZmqError;
        if (c.zmq_send(self.pub_sock, json.ptr, json.len, 0) == -1) return BusError.ZmqError;

        // A SUB socket never connects back to its own PUB, so without this,
        // two modules sharing one bus in the same process could not hear
        // each other. Dispatching the serialized form keeps the payload
        // representation identical whether a message arrived locally or
        // over the wire.
        self.dispatch(topic, json);
    }

    fn readBoundPort(sock: *anyopaque) !u16 {
        var buf: [256]u8 = undefined;
        var len: usize = buf.len;
        if (c.zmq_getsockopt(sock, c.ZMQ_LAST_ENDPOINT, &buf, &len) != 0) return BusError.ZmqError;
        const endpoint = std.mem.sliceTo(buf[0..len], 0);
        const idx = std.mem.lastIndexOfScalar(u8, endpoint, ':') orelse return BusError.ZmqError;
        return std.fmt.parseInt(u16, endpoint[idx + 1 ..], 10) catch BusError.ZmqError;
    }

    fn peerEndpoint(buf: []u8, peer: []const u8) ![:0]const u8 {
        if (std.mem.indexOf(u8, peer, "://") != null) return std.fmt.bufPrintZ(buf, "{s}", .{peer});
        return std.fmt.bufPrintZ(buf, "tcp://{s}", .{peer});
    }

    /// A bad payload or a raising subscriber must never kill the listener
    /// thread: one poisoned message would otherwise leave the node deaf for
    /// good while its heartbeat keeps reporting "ok". Runs entirely inside
    /// the RecursiveMutex, which guarantees a subscriber's handleMessage is
    /// never executed concurrently with itself on this bus.
    fn dispatch(self: *Bus, topic: []const u8, json: []const u8) void {
        self.lock.lock();
        defer self.lock.unlock();

        const list = self.subscribers.getPtr(topic) orelse return;
        if (list.items.len == 0) return;

        var parsed = std.json.parseFromSlice(std.json.Value, self.allocator, json, .{}) catch |err| {
            std.debug.print("[Framework Error] Dropping malformed payload on {s}: {}\n", .{ topic, err });
            return;
        };
        defer parsed.deinit();

        // Copy so a handler that subscribes mid-dispatch can't mutate the
        // list we're iterating.
        var copy = std.ArrayList(Subscriber).initCapacity(self.allocator, list.items.len) catch return;
        defer copy.deinit();
        copy.appendSliceAssumeCapacity(list.items);

        for (copy.items) |sub| sub.callback(sub.ptr, topic, parsed.value);
    }

    fn listenerLoop(self: *Bus) void {
        var item: c.zmq_pollitem_t = .{
            .socket = self.sub_sock,
            .fd = 0,
            .events = @intCast(c.ZMQ_POLLIN),
            .revents = 0,
        };

        while (self.running.load(.acquire)) {
            item.revents = 0;
            const rc = c.zmq_poll(&item, 1, POLL_TIMEOUT_MS);
            if (rc == -1) {
                if (!self.running.load(.acquire)) break;
                std.debug.print("[Framework Error] Listener poll failed\n", .{});
                std.time.sleep(100 * std.time.ns_per_ms);
                continue;
            }
            if (rc == 0 or (item.revents & @as(c_short, @intCast(c.ZMQ_POLLIN))) == 0) continue;

            var topic_msg: c.zmq_msg_t = undefined;
            _ = c.zmq_msg_init(&topic_msg);
            if (c.zmq_msg_recv(&topic_msg, self.sub_sock, 0) == -1) {
                _ = c.zmq_msg_close(&topic_msg);
                continue;
            }

            var more: c_int = 0;
            var more_size: usize = @sizeOf(c_int);
            _ = c.zmq_getsockopt(self.sub_sock, c.ZMQ_RCVMORE, &more, &more_size);

            const topic_bytes = @as([*]const u8, @ptrCast(c.zmq_msg_data(&topic_msg)))[0..c.zmq_msg_size(&topic_msg)];
            const topic = self.allocator.dupe(u8, topic_bytes) catch {
                _ = c.zmq_msg_close(&topic_msg);
                continue;
            };
            defer self.allocator.free(topic);
            _ = c.zmq_msg_close(&topic_msg);

            // Drop anything that doesn't match the two-frame [topic, json]
            // wire format.
            if (more == 0) continue;

            var payload_msg: c.zmq_msg_t = undefined;
            _ = c.zmq_msg_init(&payload_msg);
            if (c.zmq_msg_recv(&payload_msg, self.sub_sock, 0) == -1) {
                _ = c.zmq_msg_close(&payload_msg);
                continue;
            }
            const payload_bytes = @as([*]const u8, @ptrCast(c.zmq_msg_data(&payload_msg)))[0..c.zmq_msg_size(&payload_msg)];
            const payload = self.allocator.dupe(u8, payload_bytes) catch {
                _ = c.zmq_msg_close(&payload_msg);
                continue;
            };
            _ = c.zmq_msg_close(&payload_msg);
            defer self.allocator.free(payload);

            self.dispatch(topic, payload);
        }
    }
};

test "bus binds an ephemeral port and reports it back" {
    const bus = try Bus.init(std.testing.allocator, 0, &.{}, "127.0.0.1");
    defer bus.close();
    defer std.testing.allocator.destroy(bus);
    try std.testing.expect(bus.port != 0);
}

test "publish dispatches locally to subscribers on the same bus" {
    const bus = try Bus.init(std.testing.allocator, 0, &.{}, "127.0.0.1");
    defer bus.close();
    defer std.testing.allocator.destroy(bus);

    const Recorder = struct {
        seen: bool = false,
        rpm: i64 = 0,

        fn onMessage(ptr: *anyopaque, topic: []const u8, payload: std.json.Value) void {
            _ = topic;
            const self: *@This() = @ptrCast(@alignCast(ptr));
            self.seen = true;
            self.rpm = payload.object.get("rpm").?.integer;
        }
    };

    var recorder = Recorder{};
    try bus.subscribe("engine_data", .{ .ptr = &recorder, .callback = Recorder.onMessage });
    try bus.publish("engine_data", .{ .rpm = 4200 });

    try std.testing.expect(recorder.seen);
    try std.testing.expectEqual(@as(i64, 4200), recorder.rpm);
}
